site_name: Techie
site_url: https://jessiejizhe.github.io/techie
nav:
    - CS61A:
        - 'function': 'CS61A/ex-function.md'
        - 'recursion': 'CS61A/ex-recursion.md'
        - 'sequence': 'CS61A/ex-sequence.md'
        - 'tree': 'CS61A/ex-tree.md'
        - 'linked_list': 'CS61A/ex-linked_list.md'
        - 'CS61A-intro': 'CS61A/1-intro.md'
        - 'CS61A-function': 'CS61A/2-function.md'
        - 'CS61A-data abstraction': 'CS61A/3-data_abstraction.md'
        - 'CS61A-object oriented': 'CS61A/4-object_oriented.md'
        - 'CS61A-computer programs': 'CS61A/5-computer_programs.md'
    - DevOps:
        - 'git': 'devops/git.md'
        - 'cron': 'devops/cron.md'
        - 'unix': 'devops/unix.md'
    - Apache:
        - 'Hadoop': 'Apache/Hadoop.md'
        - 'MapReduce': 'Apache/MapReduce.md'
        - 'HDFS': 'Apache/HDFS.md'
        - 'Spark': 'Apache/Spark.md'
    - Python:
        - 'basics': 'python/basics.md'
        - 'UDF': 'python/UDF.md'
        - 'pandas': 'python/pandas.md'
        - 'plot': 'python/plot.md'
        - 'pyspark': 'python/pyspark.md'
    - SQL:
        - 'hive': 'sql/hive.md'
theme:
    name: mkdocs